config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :dashboards do
    collection do
      get :settings
    end

    member do
      get :get_download_url
    end
  end

  resources :boards do
    collection do
      get :export
      get :export_archived
    end
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    member do
      patch :update
    end
  end

  root 'static_pages#index'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def settings
    @user = current_user
  end

  def get_download_url
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_articles.html.erb
<div class="card mb-4">
  <div class="card-block">
    <h3 class="card-title">Articles</h3>

    <!-- <div class="dropdown card-title-btn-container">
      <button class="btn btn-sm btn-subtle" type="button"><em class="fa fa-list-ul"></em> View All</button>

      <button class="btn btn-sm btn-subtle dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><em class="fa fa-cog"></em></button>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton"><a class="dropdown-item" href="#"><em class="fa fa-search mr-1"></em> More info</a>
          <a class="dropdown-item" href="#"><em class="fa fa-thumb-tack mr-1"></em> Pin Window</a>
          <a class="dropdown-item" href="#"><em class="fa fa-remove mr-1"></em> Close Window</a></div>
    </div> -->

    <h6 class="card-subtitle mb-2 text-muted">Latest posts</h6>

    <div class="divider" style="margin-top: 1rem;"></div>
    <p>Nothing here yet...</p>
    <div class="articles-container">
      <!-- <div class="article border-bottom">
        <div class="col-xs-12">
          <div class="row">
            <div class="col-2 date">
              <div class="large">30</div>

              <div class="text-muted">Jun</div>
            </div>

            <div class="col-10">
              <h4><a href="#">Lorem ipsum dolor sit amet</a></h4>

              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at sodales nisl. Donec malesuada orci ornare risus finibus feugiat.</p>
            </div>
          </div>
        </div>

        <div class="clear"></div>
      </div>

      <div class="article">
        <div class="col-xs-12">
          <div class="row">
            <div class="col-2 date">
              <div class="large">30</div>

              <div class="text-muted">Jun</div>
            </div>

            <div class="col-10">
              <h4><a href="#">Lorem ipsum dolor sit amet</a></h4>

              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at sodales nisl. Donec malesuada orci ornare risus finibus feugiat.</p>
            </div>
          </div>
        </div>

        <div class="clear"></div>
      </div>

      <div class="article">
        <div class="col-xs-12">
          <div class="row">
            <div class="col-2 date">
              <div class="large">30</div>

              <div class="text-muted">Jun</div>
            </div>

            <div class="col-10">
              <h4><a href="#">Lorem ipsum dolor sit amet</a></h4>

              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at sodales nisl. Donec malesuada orci ornare risus finibus feugiat.</p>
            </div>
          </div>
        </div>

        <div class="clear"></div>
      </div> -->
    </div>
  </div>
</div>

app/views/dashboards/_download_url_section.html.erb
<% download = Download.last %>
<% if download.present? && download.created_at < DateTime.now + 1.day %>
  <div id="download-url-section" class="mb-4">
    <div class="col-md-12 download-url-section">
      <p style="color: #fff;">
        Last CSV Export Download url: <span id="download-url"><%= link_to "Download CSV", download.url ,class: "link" %></span>
      </p>
    </div>
  </div>
<% end %>

app/views/dashboards/_overview_chart.html.erb
<div class="card mb-4">
  <div class="card-block">
    <h3 class="card-title">Overview</h3>

    <div class="dropdown card-title-btn-container">
      <button class="btn btn-sm btn-subtle" type="button"><em class="fa fa-list-ul"></em> View All</button>

      <button class="btn btn-sm btn-subtle dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><em class="fa fa-cog"></em></button>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton"><a class="dropdown-item" href="#"><em class="fa fa-search mr-1"></em> More info</a>
          <a class="dropdown-item" href="#"><em class="fa fa-thumb-tack mr-1"></em> Pin Window</a>
          <a class="dropdown-item" href="#"><em class="fa fa-remove mr-1"></em> Close Window</a></div>
    </div>

    <h6 class="card-subtitle mb-2 text-muted">Latest traffic stats</h6>

    <div class="canvas-wrapper">
      <canvas class="main-chart" id="line-chart" height="200" width="600"></canvas>
    </div>
  </div>
</div>

<script>
  window.onload = function () {
  	var chart1 = document.getElementById("line-chart").getContext("2d");
  	window.myLine = new Chart(chart1).Line(lineChartData, {
  	responsive: true,
  	scaleLineColor: "rgba(0,0,0,.2)",
  	scaleGridLineColor: "rgba(0,0,0,.05)",
  	scaleFontColor: "#c5c7cc"
  	});
  };
</script>

app/views/dashboards/_recent_orders_table.html.erb
<div class="card mb-4">
  <div class="card-block">
    <h3 class="card-title">Recent Orders</h3>

    <div class="dropdown card-title-btn-container">
      <button class="btn btn-sm btn-subtle" type="button"><em class="fa fa-list-ul"></em> View All</button>

      <button class="btn btn-sm btn-subtle dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><em class="fa fa-cog"></em></button>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton"><a class="dropdown-item" href="#"><em class="fa fa-search mr-1"></em> More info</a>
          <a class="dropdown-item" href="#"><em class="fa fa-thumb-tack mr-1"></em> Pin Window</a>
          <a class="dropdown-item" href="#"><em class="fa fa-remove mr-1"></em> Close Window</a></div>
    </div>

    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Order #</th>

            <th>Product</th>

            <th>Customer</th>

            <th>Status</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>0001</td>

            <td>Product Name 1</td>

            <td>Customer 1</td>

            <td>Complete</td>
          </tr>

          <tr>
            <td>0002</td>

            <td>Product Name 2</td>

            <td>Customer 2</td>

            <td>Complete</td>
          </tr>

          <tr>
            <td>0003</td>

            <td>Product Name 3</td>

            <td>Customer 3</td>

            <td>Processing</td>
          </tr>

          <tr>
            <td>0004</td>

            <td>Product Name 4</td>

            <td>Customer 4</td>

            <td>Pending</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/dashboards/_timeline.html.erb
<div class="card mb-4">
  <div class="card-block">
    <h3 class="card-title">Feature Timeline</h3>

    <h6 class="card-subtitle mb-2 text-muted">Here is what we have upcoming</h6>

    <ul class="timeline">
      <li>
        <div class="timeline-badge primary"><em class="fa fa-search"></em></div>

        <div class="timeline-panel">
          <div class="timeline-heading">
            <h5 class="timeline-title mt-2">Card Management</h5>
          </div>

          <div class="timeline-body">
            <p>View, search and filter all Trello cards here with a birds eye view.</p>
            <p class="card-text"><small class="text-muted">December 2017</small></p>
          </div>
        </div>
      </li>
      <li>
        <div class="timeline-badge"><em class="fa fa-eye"></em></div>

        <div class="timeline-panel">
          <div class="timeline-heading">
            <h5 class="timeline-title mt-2">Sprint Overview</h5>
          </div>

          <div class="timeline-body">
            <p>Look at all cards within a sprint and identify velocity based on burndown chart.</p>
            <p class="card-text"><small class="text-muted">January 2018</small></p>
          </div>
        </div>
      </li>
      <li>
        <div class="timeline-badge"><em class="fa fa-bell"></em></div>

        <div class="timeline-panel">
          <div class="timeline-heading">
            <h5 class="timeline-title mt-2">Notifications</h5>
          </div>

          <div class="timeline-body">
            <p>Better notifications so you don't miss out what is happening in Trello.</p>
            <p class="card-text"><small class="text-muted">February 2018</small></p>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/dashboards/_todo_list.html.erb
<div class="card mb-4">
  <div class="card-block">
    <h3 class="card-title">Todo List</h3>

    <div class="dropdown card-title-btn-container">
      <button class="btn btn-sm btn-subtle dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><em class="fa fa-cog"></em></button>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton"><a class="dropdown-item" href="#"><em class="fa fa-search mr-1"></em> More info</a>
        <a class="dropdown-item" href="#"><em class="fa fa-thumb-tack mr-1"></em> Pin Window</a>
        <a class="dropdown-item" href="#"><em class="fa fa-remove mr-1"></em> Close Window</a></div>
    </div>

    <h6 class="card-subtitle mb-2 text-muted">A simple checklist</h6>

    <ul class="todo-list mt-2">
      <li class="todo-list-item">
        <div class="form-check">
          <input type="checkbox" id="checkbox-1" />

          <label for="checkbox-1">Make coffee</label>

          <div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
        </div>
      </li>
      <li class="todo-list-item">
        <div class="form-check">
          <input type="checkbox" id="checkbox-2" />

          <label for="checkbox-2">Check emails</label>

          <div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
        </div>
      </li>
      <li class="todo-list-item">
        <div class="form-check">
          <input type="checkbox" id="checkbox-3" />

          <label for="checkbox-3">Reply to Jane</label>

          <div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
        </div>
      </li>
      <li class="todo-list-item">
        <div class="form-check">
          <input type="checkbox" id="checkbox-4" />

          <label for="checkbox-4">Work on the new design</label>

          <div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
        </div>
      </li>
      <li class="todo-list-item">
        <div class="form-check">
          <input type="checkbox" id="checkbox-5" />

          <label for="checkbox-5">Get feedback</label>

          <div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
        </div>
      </li>
    </ul>

    <div class="card-footer todo-list-footer">
      <div class="input-group">
        <input id="btn-input" type="text" class="form-control input-md" placeholder="Add new task" /><span class="input-group-btn">
          <button class="btn btn-primary btn-md" id="btn-todo">Add</button>
      </span></div>
    </div>
  </div>
</div>

app/views/dashboards/_trello_boards.html.erb
<div class="card mb-4">
  <div class="card-block">
    <h3 class="card-title">My Trello Boards</h3>
    <h6 class="card-subtitle mb-2 text-muted">Most recently active</h6>

    <% if current_user.boards.present? %>
      <% current_user.boards.order(date_last_activity: :desc).each do |board| %>
        <div class="row">
          <div class="col-md-9">
            <h5 class="pt-1"><%= board.name %></h6>
            <p>
              <%= board.date_last_activity.strftime("%d %B %Y %r") %>
            </p>
          </div>
          <div class="col-md-3">
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Action
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <p class="dropdown-header" style="padding-top: 0px;"><%= board.name %></p>
                <hr style="margin:0px; /">
                <%= link_to "Export Open", export_boards_path(user_id: current_user.id, board_id: board.trello_board_id), class: "dropdown-item" %>
                <%= link_to "Export Archived", export_archived_boards_path(user_id: current_user.id, board_id: board.trello_board_id), class: "dropdown-item" %>
              </div>
            </div>

          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/dashboards/_welcome_jumbotron.html.erb
<div class="jumbotron">
  <h1 class="mb-4">Welcome to TrelloMax</h1>
  <p class="lead">This is a simple web tool to maximise your productivity using Trello.</p>
  <p>For now, you are only able to export your Trello cards into a CSV file. More functionality will be coming soon.</p>
</div>

app/views/dashboards/get_download_url.js.erb
$("#download-url").html("new url");

app/views/dashboards/index.html.erb
<div class="container-fluid" id="wrapper">
	<div class="row">
		<main class="col-xs-12 col-sm-8 offset-sm-4 col-lg-9 offset-lg-3 col-xl-10 offset-xl-2 pt-3 pl-4">
			<header class="page-header row justify-center">
				<div class="col-md-6 col-lg-8" >
					<h1 class="float-left text-center text-md-left">Dashboard</h1>
				</div>
				<%= render "layouts/nav_avatar" %>

				<div class="clear"></div>
			</header>

			<section class="row">
				<div class="col-sm-12">
					<section class="row">
						<div class="col-md-12 col-lg-8">
							<%= render "layouts/notice" %>
							<%= render "dashboards/welcome_jumbotron" %>
							<%= render "dashboards/download_url_section" %>
							<!-- <%= render "dashboards/overview_chart" %> -->
							<!-- <%= render "dashboards/recent_orders_table" %> -->
							<%= render "dashboards/trello_boards" %>
						</div>

						<div class="col-md-12 col-lg-4">
							<%= render "dashboards/articles" %>
							<%= render "dashboards/timeline" %>
							<!-- <%= render "dashboards/todo_list" %> -->
						</div>
					</section>
				</div>
			</section>
		</main>
	</div>
</div>

app/views/dashboards/settings.html.erb
<div class="container">
  <div class="row">
    <main class="col-xs-12 col-sm-8 offset-sm-4 col-lg-9 offset-lg-3 col-xl-10 offset-xl-2 pt-3 pl-4" style="margin-top:50px;">
      <%= render "layouts/notice" %>
      <h4>Update Trello Settings</h4> You can get your Trello key and token here <%= link_to "Trello API Key & Token", "https://trello.com/app-key/", target: "_blank" %>
      <%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
        <div class="form-group">
          <%= f.input :trello_key, autofocus: true, required: true %>
        </div>

        <div class="form-group">
          <%= f.input :trello_token, required: true %>
        </div>

        <div>
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </main>
  </div>
</div>