config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :dashboards do
    collection do
      get :settings
    end

    member do
      get :get_download_url
    end
  end

  resources :boards do
    collection do
      get :export
      get :export_archived
    end
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    member do
      patch :update
    end
  end

  root 'static_pages#index'
end

app/views/layouts/_dashboard_nav.html.erb
<nav class="sidebar col-xs-12 col-sm-4 col-lg-3 col-xl-2 bg-faded sidebar-style-1">
  <h1 class="site-title">
    <%= link_to root_path, method: :get  do %>
      <em class="fa fa-trello"></em> TrelloMax
    <% end %>
  </h1>

  <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><em class="fa fa-bars"></em></a>

  <ul class="nav nav-pills flex-column sidebar-nav">
    <li class="nav-item">
      <%= link_to dashboards_path, class: "nav-link" do %>
        <em class="fa fa-dashboard"></em> Dashboard
      <% end %>
      <%= link_to settings_dashboards_path, class: "nav-link" do %>
        <em class="fa fa-cog"></em> Settings
      <% end %>
    </li>
  </ul>

  <%= link_to destroy_user_session_path, method: :delete, class: "logout-button" do %>
    <em class="fa fa-power-off"></em> Signout
  <% end %>
</nav>

app/views/layouts/_nav.html.erb
<nav class="navbar sticky-top navbar-light bg-faded">
	<ul class="nav justify-content-end">
		<%= link_to "TrelloMax", root_path, class: "navbar-brand mr-auto" %>
		<% if current_user.present? %>
			<%= render "layouts/nav_avatar" %>
		<% else %>
			<li class="nav-item">
				<%= link_to "Login", new_user_session_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "Register", new_user_registration_path, class: "btn btn-primary" %>
			</li>
		<% end %>
	</ul>
</nav>

app/views/layouts/_nav_avatar.html.erb
<div class="dropdown user-dropdown col-md-6 col-lg-4 text-center text-md-right">
  <a class="btn btn-stripped dropdown-toggle" href="https://example.com" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= image_tag("profile-pic.jpg", alt: "profile photo", class: "circle float-left profile-photo", width: "50", height: "auto") %>

    <div class="username mt-1">
      <h4 class="mb-1"><%= current_user.name %></h4>
      <h6 class="text-muted">Super Admin</h6>
    </div>
  </a>

  <div class="dropdown-menu dropdown-menu-right" style="margin-right: 1.5rem;" aria-labelledby="dropdownMenuLink">
    <%= link_to dashboards_path, class: "dropdown-item" do %>
      <em class="fa fa-dashboard"></em> Dashboard</a>
    <% end %>
    <a class="dropdown-item" href="#"><em class="fa fa-sliders mr-1 disabled"></em> Preferences</a>
    <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
      <em class="fa fa-power-off mr-1"></em> Logout</a>
    <% end %>
   </div>
</div>

app/views/layouts/_notice.html.erb
<% if flash.present? %>
  <%- flash.each do |name, msg| -%>
    <% name = name.eql?("notice") ? "info" : name %>
    <% name = (name.include?("alert") || name.include?("error")) ? "warning" : name %>
    <div class="alert alert-<%= name %> alert-dismissable" role="alert">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  <%- end -%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  	<meta name="description" content="">
  	<meta name="author" content="">
  	<title>TrelloMax | Maximise Trello Experience</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- navigation bar left or top  -->
    <% if params[:controller] == "dashboards" %>
      <%= render "layouts/dashboard_nav" %>
    <% else %>
      <%= render "layouts/nav" %>
    <% end %>

    <%= yield %>
  </body>
</html>